name: AkEffect
version: 1.4.6
authors: [coder014,HigherSY]
main: org.akteam.akeffect.AkEffect
api-version: "1.14"

commands:
  akeffect:
    description: Control this plugin.
    usage: /akeffect <reload>
  fuckme:
    description: Create a fake explore on the player commanding but do damage to other players around.
    usage: /fuckme
  shazam:
    description: Make player a superman with strong positive effects.Need to have food level 16 at least.
    usage: /shazam
  rocket:
    description: Create a fired arrow which takes the player in the air.
    usage: /rocket
  particle4p:
    description: Create some different particle effects for each player
    usage: /particle4p [change/start/stop]
    aliases: [p4p]
